export enum ERROR_CODES {
  // Common
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  BAD_REQUEST = "BAD_REQUEST",
  NOT_FOUND = "NOT_FOUND",
  METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED",
  INTERNAL_ERROR = "INTERNAL_ERROR",
  CONFLICT = "CONFLICT",
  VALIDATION_ERROR = "VALIDATION_ERROR",

  // Payload / Validation
  INVALID_PAYLOAD = "INVALID_PAYLOAD",
  MISSING_REQUIRED_FIELDS = "MISSING_REQUIRED_FIELDS",
  INVALID_AMOUNT = "INVALID_AMOUNT",
  INVALID_METHOD_ID = "INVALID_METHOD_ID",
  MISSING_IDEMPOTENCY_KEY = "MISSING_IDEMPOTENCY_KEY",
  INVALID_IDEMPOTENCY_KEY = "INVALID_IDEMPOTENCY_KEY",
  INVALID_IDEMPOTENCY_KEY_FORMAT = "INVALID_IDEMPOTENCY_KEY_FORMAT",
  INVALID_PAYMENT_ID = "INVALID_PAYMENT_ID",
  INVALID_PAYMENT_ID_FORMAT = "INVALID_PAYMENT_ID_FORMAT",
  INVALID_ORDER_ID = "INVALID_ORDER_ID",
  INVALID_ORDER_ID_FORMAT = "INVALID_ORDER_ID_FORMAT",
  INVALID_ORDER_ITEM_ID = "INVALID_ORDER_ITEM_ID",
  INVALID_ACTION = "INVALID_ACTION",
  CONFLICTING_IDEMPOTENCY_KEY_FORMATS = "CONFLICTING_IDEMPOTENCY_KEY_FORMATS",
  
  // Specific Entities
  VENDOR_NOT_FOUND = "VENDOR_NOT_FOUND",
  PAYMENT_ALREADY_COMPLETED = "PAYMENT_ALREADY_COMPLETED",

  // Specific / Integration
  RAZORPAY_SERVER_ERROR = "RAZORPAY_SERVER_ERROR",
  RAZORPAY_CLIENT_ERROR = "RAZORPAY_CLIENT_ERROR",
  PAYMENT_VERIFICATION_FAILED = "PAYMENT_VERIFICATION_FAILED",
  ORDER_MISMATCH = "ORDER_MISMATCH",
  PAYMENT_NOT_CAPTURED = "PAYMENT_NOT_CAPTURED",
  AMOUNT_MISMATCH = "AMOUNT_MISMATCH",
  PAYMENT_UPDATE_FAILED = "PAYMENT_UPDATE_FAILED",
  RAZORPAY_NOT_CONFIGURED = "RAZORPAY_NOT_CONFIGURED",
  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",
  RATE_LIMIT = "RATE_LIMIT",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
  BAD_GATEWAY = "BAD_GATEWAY"
}
