
ALTER TABLE payments ADD COLUMN IF NOT EXISTS upi_id text DEFAULT NULL;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS qr_code_url text DEFAULT NULL;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS payment_proof text DEFAULT NULL;
